### ISSUE TITLE
Enigma M3 Cipher

### ISSUE THREAD

**Issue by Arszilla** [jameslyons/pycipher#10]
Is the cipher broken? I can't get a decode on other sites using James' code.

This is the code I wrote to try the module:

https://paste.pydis.com/serazawora.py

This is my output using random rings etc:

> Your deciphered text: JYPVNHK
> Your first rotor: 6
> Your second rotor: 6
> Your third rotor: 7
> Your first position: 9 / I
> Your second position: 22 / V
> Your third position: 8 / H
> Your first ring: 26 / Z
> Your second ring: 6 / F
> Your third ring: 17 / Q
> Your reflector: B
> Your plugboard: [('h', 'p'), ('m', 'g'), ('w', 'f'), ('y', 't'), ('v', 'i'), ('o', 'r'), ('u', 'k'), ('q', 'z'), ('b', 's'), ('l', 'a')]

Now I used Cryptii to decode and got this when I input those stuff above: http://i63.tinypic.com/2ivxvnr.png

Not sure if I am doing something wrong or the module's code is broken

**Comment by Arszilla** [comment]
Bumping as I still need assistance.

**Comment by jameslyons** [comment]
Hi arszilla,
sorry I didn't get back to you earlier. Am I understanding correctly that the ciphertext is only 7 characters? if so that is the reason it doesn't work. To successfully crack the messages you'll need more, I can't quite remember how much but a few hundred characters should be plenty. The reason for this is that the code uses a statistical model of english to know when it has found the correct settings, and unfortunately the statistical models don't work on short pieces of text. 

Feel free to ask more questions.

**Comment by jameslyons** [comment]
sorry, i think i misunderstood what you were doing. I have a lot of projects around the internet :) You are just trying to encipher/decipher text with a known key. I'll have a look at the code and get back to you.

**Comment by Arszilla** [comment]
I randomly generated rotors, rings, settings and plugboard for the enigma while using UKW B reflector. For some reason I cannot get a 'check' of the enciphered output on sites like Cryptii; the text is not being decoded. That means either my code is wrong or there is a bug/error in enigma @ pycipher/enigma.py

Another example:

```
Your deciphered text: POIEQEQBVFPJAIKPVWNFYQBMUEXJHPHXYXWBARTJNLONMIBRMVHZZF
Your first rotor: 5
Your second rotor: 2
Your third rotor: 3
Your first position: 13 / M
Your second position: 7 / G
Your third position: 13 / M
Your first ring: 2 / B
Your second ring: 15 / O
Your third ring: 7 / G
Your reflector: B
Your plugboard: [('a', 'd'), ('x', 'p'), ('t', 'c'), ('v', 'b'), ('j', 'r'), ('o', 'h'), ('i', 'f'), ('u', 'l'), ('q', 'y'), ('k', 'n')]
```

http://i68.tinypic.com/2eex8uh.png

This time I used dCode to decode/decipher it

**Comment by jameslyons** [comment]
i figured out the problem i think
your plugboard is in lowercase, so the comparisons on line 85 and 86 of enigma.py aren't happening, as a result its equivalent to no plugboard being applied. Try it with uppercase plugboard letters. I'll fix up the code at some point when I get the time.

**Comment by jameslyons** [comment]
Also the image you sent in the first comment from cryptii uses rotors 6,6,6 but you have 6,6,7 in the example. 

> Now I used Cryptii to decode and got this when I input those stuff above: http://i63.tinypic.com/2ivxvnr.png

**Comment by Arszilla** [comment]
I think that fixed it:

```
Your deciphered text: LDZPLODYWVXHXXWD
Your first rotor: 3
Your second rotor: 7
Your third rotor: 3
Your first position: 22 / V
Your second position: 5 / E
Your third position: 11 / K
Your first ring: 1 / A
Your second ring: 11 / K
Your third ring: 14 / N
Your reflector: B
Your plugboard: [('I', 'Y'), ('C', 'T'), ('L', 'Z'), ('A', 'F'), ('D', 'H'), ('E', 'K'), ('B', 'W'), ('Q', 'P'), ('X', 'R'), ('J', 'O')]
```

http://i64.tinypic.com/21nnqyd.png

Only issue is the spacing in online decoding and perhaps getting the plugboard to be outtputed as 

``IY CT LZ AF DH EK BW QP XR JO`` 

instead of 

``
[('I', 'Y'), ('C', 'T'), ('L', 'Z'), ('A', 'F'), ('D', 'H'), ('E', 'K'), ('B', 'W'), ('Q', 'P'), ('X', 'R'), ('J', 'O')]
``

**Comment by jameslyons** [comment]
excellent. I'll close this issue, feel free to open another one if you have any more questions.
