### ISSUE TITLE
The implementation of Enigma cipher

### ISSUE THREAD

**Issue by ZM-J** [jameslyons/pycipher#16]
Why does the result differ from results in dcode.fr?

https://www.dcode.fr/enigma-machine-cipher

For example, if we use the same plaintext and the same settings, the ciphertexts differ.

**Comment by jameslyons** [comment]
Ive used this quite a bit and never had any problems, could you add some
screen shots or something? Perhaps compare to a 3rd enigma to determine
which implementation has the problem?

**Comment by ZM-J** [comment]
Consider the following encryption and decryption:

<img width="587" alt="" src="https://user-images.githubusercontent.com/21689514/147088982-480dba6e-870c-4762-89ba-54fdc972caf1.png">

so we use the following code to decrypt:

```py
import pycipher

enc = pycipher.Enigma(settings=('R', 'N', 'G'), rotors=(2,1,3), ringstellung=('E', 'D', 'G'),
        steckers=[('A', 'T'), ('B','V'), ('C','F'), ('E','N'), ('G','Y'), ('H','O'), ('I','W'), ('L','U'), ('M','Z'), ('Q','X')])


c = 'LIZIJWMHIXW'
print(enc.decipher(c))
```

However, we got `GXNTTORISET`, which is incorrect.

**Comment by ZM-J** [comment]
Okay so now I tend to believe that the implementation of dcode.fr has some problem.

Thanks for your response.
