### ISSUE TITLE
Push to pypi

### ISSUE THREAD

**Issue by gonvaled** [jameslyons/pycipher#4]
Would it be possible to push a stable release to pypi?

**Comment by jameslyons** [comment]
when you say stable, do you mean a release version that starts with a 1.*? or are there bugs in the pypi version that need to be fixed? I can update the pypi version with the current github version no problem.

**Comment by gonvaled** [comment]
To tell you the truth, I do not really remember, but probably I was referring to [this](https://github.com/jameslyons/pycipher#install):

```
pip install git+git://github.com/jameslyons/pycipher
```

Maybe update the readme with a reference to pypi? It is usually cleaner to refer to pypi than to github repos.

**Comment by jameslyons** [comment]
This was fixed.
